// Code generated by controller-gen style scaffold. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func copyStringMap(in map[string]string) map[string]string {
	if in == nil {
		return nil
	}
	out := make(map[string]string, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	if in.Extra != nil {
		out.Extra = make(corev1.ResourceList, len(in.Extra))
		for k, v := range in.Extra {
			out.Extra[k] = v.DeepCopy()
		}
	}
}

func (in *RuntimeSpec) DeepCopyInto(out *RuntimeSpec) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	out.NodeSelector = copyStringMap(in.NodeSelector)
}

func (in *ModelProject) DeepCopyInto(out *ModelProject) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.Defaults.Runtime.DeepCopyInto(&out.Spec.Defaults.Runtime)
	if in.Status.Conditions != nil {
		out.Status.Conditions = make([]metav1.Condition, len(in.Status.Conditions))
		copy(out.Status.Conditions, in.Status.Conditions)
	}
}

func (in *ModelProject) DeepCopy() *ModelProject {
	if in == nil {
		return nil
	}
	out := new(ModelProject)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelProject) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelProjectList) DeepCopyInto(out *ModelProjectList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelProject, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelProjectList) DeepCopy() *ModelProjectList {
	if in == nil {
		return nil
	}
	out := new(ModelProjectList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelProjectList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *Experiment) DeepCopyInto(out *Experiment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec.Datasets.Instruction != nil {
		x := *in.Spec.Datasets.Instruction
		out.Spec.Datasets.Instruction = &x
	}
	if in.Spec.Datasets.Evaluation != nil {
		x := *in.Spec.Datasets.Evaluation
		out.Spec.Datasets.Evaluation = &x
	}
	in.Spec.Runtime.DeepCopyInto(&out.Spec.Runtime)
	if in.Spec.EvaluationSuiteRef != nil {
		x := *in.Spec.EvaluationSuiteRef
		out.Spec.EvaluationSuiteRef = &x
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}
func (in *Experiment) DeepCopy() *Experiment {
	if in == nil {
		return nil
	}
	out := new(Experiment)
	in.DeepCopyInto(out)
	return out
}
func (in *Experiment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ExperimentList) DeepCopyInto(out *ExperimentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]Experiment, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ExperimentList) DeepCopy() *ExperimentList {
	if in == nil {
		return nil
	}
	out := new(ExperimentList)
	in.DeepCopyInto(out)
	return out
}
func (in *ExperimentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelRun) DeepCopyInto(out *ModelRun) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.Runtime.DeepCopyInto(&out.Spec.Runtime)
	if in.Status.ResolvedDatasets != nil {
		out.Status.ResolvedDatasets = make(map[string]ResolvedDatasetRef, len(in.Status.ResolvedDatasets))
		for k, v := range in.Status.ResolvedDatasets {
			out.Status.ResolvedDatasets[k] = v
		}
	}
	if in.Status.LatestCheckpoint != nil {
		x := *in.Status.LatestCheckpoint
		out.Status.LatestCheckpoint = &x
	}
	if in.Status.ArtifactRef != nil {
		x := *in.Status.ArtifactRef
		out.Status.ArtifactRef = &x
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}
func (in *ModelRun) DeepCopy() *ModelRun {
	if in == nil {
		return nil
	}
	out := new(ModelRun)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelRun) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelRunList) DeepCopyInto(out *ModelRunList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelRun, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelRunList) DeepCopy() *ModelRunList {
	if in == nil {
		return nil
	}
	out := new(ModelRunList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelRunList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelArtifact) DeepCopyInto(out *ModelArtifact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec.Tokenizer != nil {
		x := *in.Spec.Tokenizer
		out.Spec.Tokenizer = &x
	}
	if in.Spec.Datasets != nil {
		out.Spec.Datasets = append([]DatasetProvenance(nil), in.Spec.Datasets...)
	}
	if in.Status.Evaluations != nil {
		out.Status.Evaluations = make(map[string]EvaluationStatus, len(in.Status.Evaluations))
		for k, v := range in.Status.Evaluations {
			vv := v
			if v.Metrics != nil {
				vv.Metrics = make(map[string]float64, len(v.Metrics))
				for mk, mv := range v.Metrics {
					vv.Metrics[mk] = mv
				}
			}
			out.Status.Evaluations[k] = vv
		}
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}
func (in *ModelArtifact) DeepCopy() *ModelArtifact {
	if in == nil {
		return nil
	}
	out := new(ModelArtifact)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelArtifact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelArtifactList) DeepCopyInto(out *ModelArtifactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelArtifact, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelArtifactList) DeepCopy() *ModelArtifactList {
	if in == nil {
		return nil
	}
	out := new(ModelArtifactList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelArtifactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelRelease) DeepCopyInto(out *ModelRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.Serving.Resources.DeepCopyInto(&out.Spec.Serving.Resources)
	if in.Status.Conditions != nil {
		out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	}
}
func (in *ModelRelease) DeepCopy() *ModelRelease {
	if in == nil {
		return nil
	}
	out := new(ModelRelease)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ModelReleaseList) DeepCopyInto(out *ModelReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]ModelRelease, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *ModelReleaseList) DeepCopy() *ModelReleaseList {
	if in == nil {
		return nil
	}
	out := new(ModelReleaseList)
	in.DeepCopyInto(out)
	return out
}
func (in *ModelReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
